### ISSUE TITLE
Missing files to compile for linux

### ISSUE THREAD

**Issue by FalcoGer** [Konradrundfunk/Amateurfunktrainer#6]
No compilation instructions or dependencies were provided. So I ran the default steps to compile

```bash
git clone --recursive git@github.com:Konradrundfunk/amateurfunktrainer.git
cd amateurfunktrainer/linux
mkdir build
cd build
cmake ..
```

The following errors appears.

```text
CMake Error at flutter/CMakeLists.txt:6 (include):
  include could not find requested file:

    /home/paul/repositories/amateurfunktrainer/linux/flutter/ephemeral/generated_config.cmake


CMake Error at flutter/generated_plugins.cmake:12 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux" which is not
  an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:69 (include)


-- Configuring incomplete, errors occurred!
See also "/home/paul/repositories/amateurfunktrainer/linux/build/CMakeFiles/CMakeOutput.log".
```

**Comment by FalcoGer** [comment]
I figured out how to build flutter projects, I think (build instructions would still be nice), but I still get errors.

I installed flutter and ran from the base directory

```
flutter build linux
```

No artifacts were created at this time. I then ran

```
cd linux
mkdir build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

And got the following error

```
[ 14%] Generating ../../flutter/ephemeral/libflutter_linux_gtk.so, ../../flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, ../../flutter/ephemeral/flutter_linux/fl_binary_codec.h, ../../flutter/ephemeral/flutter_linux/fl_binary_messenger.h, ../../flutter/ephemeral/flutter_linux/fl_dart_project.h, ../../flutter/ephemeral/flutter_linux/fl_engine.h, ../../flutter/ephemeral/flutter_linux/fl_json_message_codec.h, ../../flutter/ephemeral/flutter_linux/fl_json_method_codec.h, ../../flutter/ephemeral/flutter_linux/fl_message_codec.h, ../../flutter/ephemeral/flutter_linux/fl_method_call.h, ../../flutter/ephemeral/flutter_linux/fl_method_channel.h, ../../flutter/ephemeral/flutter_linux/fl_method_codec.h, ../../flutter/ephemeral/flutter_linux/fl_method_response.h, ../../flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, ../../flutter/ephemeral/flutter_linux/fl_plugin_registry.h, ../../flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, ../../flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, ../../flutter/ephemeral/flutter_linux/fl_string_codec.h, ../../flutter/ephemeral/flutter_linux/fl_value.h, ../../flutter/ephemeral/flutter_linux/fl_view.h, ../../flutter/ephemeral/flutter_linux/flutter_linux.h,_phony_
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      _Array.[] (dart:core-patch/array.dart:10:36)
#1      main (file:///home/paul/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.dart:12:37)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
make[2]: *** [flutter/CMakeFiles/flutter_assemble.dir/build.make:93: ../flutter/ephemeral/libflutter_linux_gtk.so] Error 255
make[1]: *** [CMakeFiles/Makefile2:145: flutter/CMakeFiles/flutter_assemble.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
